/*!
Turia Trivial is a Rust webapp for playing Trivial with your classmates, adding your own quewstions, modify the questions, and... have fun!
*/

#![warn(missing_docs)]

/// A module for authentication (/api/auth)
pub mod auth_handler;
/// A module for getting the parameters that are needed (passwords) from a text file
pub mod config;
/// A module that specifies the messages returned when an error has occured
pub mod error;
/// A module for uploading the images of the questions (/api/image)
pub mod image;
/// A module with the model DB
pub mod models;
/// A module for adding, removing or filtering a quesiton (/api/question and /api/filter_question)
pub mod question;
/// A module for creating users and assigning the courses (/api/add_user)
pub mod register_handler;
/// The DB schema (auto-generated by Diesel)
pub mod schema;
/// Some utilities for the rest of the program (hash_password)
pub mod util;
